//
// Created by erick on 8/24/18.
//

#ifndef MORDEROPENGLUDEMYTUTORIAL_COMMONVALUES_H
#define MORDEROPENGLUDEMYTUTORIAL_COMMONVALUES_H

#include <GL/glew.h>
#include "../Rendering/stb_image.h"

const int
	MAX_MATERIALS_TEXTURES = 3, 
	MAX_GLOBAL_TEXTURE_UNITS = 16, 
	MAX_DRAWING_TEXTURE_UNITS = 16;

/**
 * Uniforms used
 * */
enum ShaderType{
	BASIC_SHADER,

	DIRECTIONAL_LIGHT_SHADOW_MAP_SHADER,
	OMNI_DIRECTIONAL_LIGHT_SHADOW_MAP_SHADER,
	SKY_BOX_SHADER,

	FORWARD_AMBIENT_SHADER,
    FORWARD_DIRECTIONAL_LIGHT_SHADER,
    FORWARD_POINT_LIGHT_SHADER,
    FORWARD_SPOT_LIGHT_SHADER,

	FOG_SHADER,
    TERRAIN_SHADER,

	NUM_SHADER_TYPES
};

enum LightType{
    DIRECTIONAL_LIGHT,
    POINT_LIGHT,
    SPOT_LIGHT,

    NUM_LIGHT_TYPES
};

enum TextureTypeEnum {
	DIFFUSE_TEXTURE,
	DIFFUSE_TEXTURE_ATLAS,
	SPECULAR_TEXTURE,
	SPECULAR_TEXTURE_ATLAS,
	BACKGROUND_TEXTURE,
	R_TEXTURE,
	G_TEXTURE,
	B_TEXTURE,
	BLEND_MAP_TEXTURE,
	HEIGHT_MAP_TEXTURE
};
#endif //MORDEROPENGLUDEMYTUTORIAL_COMMONVALUES_H
